### ISSUE TITLE
Reworking Allergies

### ISSUE THREAD

**Issue by Dog** [exercism/xpython#187]
Looking through Allergies, I think it may make sense to do a rewrite. The exercise seems to be intended to practice using binary to represent state, but in execution we really use the Allergy class like a container. Its really a set. We look up allergies with the is_allergic_to function with the allergy as a key. If I were writing the class, I'd probably make it work along these lines:

```python
allergies = ['eggs', 'peanuts', 'shellfish', 'strawberries', 'tomatoes', 'chocolate', 'pollen', 'cats']
example = Allergies(*allergies)

if 'eggs' in example:
    print 'I am allergic to eggs'

if 'dogs' not in example:
    print 'I am not allergic to dogs'

example.add('dogs')
if 'dogs' in example:
    print 'I am allergic to dogs'

allergy_list = list(example)
```

Where the value of `allergy_list` is:
`['eggs', 'peanuts', 'shellfish', 'strawberries', 'tomatoes', 'chocolate', 'pollen', 'cats', 'dogs']`

I'm a bit conflicted by this exercise. It causes problems with order as seen in https://github.com/exercism/xpython/issues/186 and makes adding or removing allergies harder than it should be.

Does anyone have any input?

**Comment by kytrinyx** [comment]
I originally made it to introduce the idea of bitmasks to some people I was mentoring. I think that it could probably benefit from an overhaul, and am absolutely open to suggestions.

**Comment by Dog** [comment]
What if we did bit masks through rgb and greyscale conversion? You take in a bunch of values simulating an image that you are converting. You could also extend it with another exercise to simulate compression in an image.

**Comment by kytrinyx** [comment]
I think that sounds like a great exercise!

**Comment by spthm** [comment]
Hope you don't mind if I throw my 2c into this, before acting on #186.

+1 on the rgb/greyscale conversion. Actually, writing a code to convert 24-bit color to RGB (or hex) is the simplest example I can think of that both _requires_ bit manipulation __and__ isn't _completely abstract_, like e.g. a hash function.

If you wanted to make the Allergies test point toward using a bitfield, it might be an idea to write the numbers in the test file in binary form, i.e. `0b101` rather than `5`.

In addition to problem(s) with the test, I think the readme could also be better. (Perhaps this is an issue for `x-common`?) It refers to 'scores' when they're really (bit-)flags. '(bit-)flags' may also be confusing, but I would not expect newcomers to see powers of two and think 'aha, bits!' Or, in fact, be anything other than confused by the 'scoring' system.

Obviously you don't want to give the game away, and figuring it out is part of the exercise. But I suspect this is currently a you-get-it-or-you-don't problem, so some more hints would _not_ be detrimental to the learning value.

**Comment by kytrinyx** [comment]
@spthm Yeah, you're probably right that the README could be improved (and that it's an issue for x-common) I'm just not sure in what way, without (as you say) giving the game away.

Writing the numbers in binary form in the test is an interesting suggestion.

**Comment by Dog** [comment]
@kytrinyx I can mock up an exercise. Would you like it focused on only RGB/Greyscale conversion, or should I also consider adding in a lossy compression component? Would I propose it via a pull request in x-common with the original test cases as a pull request in xpython?

@spthm I'll try to take a look into that by Friday. I think you are right about it being a you-get-it-or-you-don't problem. I know when reddit did their exercism team for python a lot of people struggled with that problem as is.

**Comment by kytrinyx** [comment]
Yeah, I'd love to see a suggestion for the exercise. Two PRs that reference each other would be great -- one in x-common where all the track maintainers can discuss the problem itself, and another with the test cases in python.

I don't know if the lossy compression component makes sense here--I think I just don't have a good picture of what it would look like with or without it.

**Comment by Dog** [comment]
I did some more thinking about it, and I think doing lossy compression is too much. 

Initially I was thinking I could have people make a data structure for their image, and then implement a naive solution using that structure. The data structure would be composed of chunks for the full image. Each chunk represents a region of pixels with a color value. If a pixel is within a tolerance of its neighbor, you would average the pixels and combine them into a chunk.

**Comment by kytrinyx** [comment]
Yeah, that sounds complicated, let's just stick with the rgb/grayscale piece.
