### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by rahmonov** [exercism/xpython#309]
Isn't it better to run the tests like `python bob_test.py`? Without installing a third party `pytest`

**Comment by behrtam** [comment]
Thinking about this (maybe I miss something) using `py.test` doesn't add any value in our case. The `unittest` module also offers the option `-f, --failfast` that acts like `-x` option of `py.test`. Also the output looks almost the same.

Normally one would choose `py.test` because it reduces the needed boiler plate code (but we do use the `unittest` module) and it is more `idiomatic` python than the `junit` (Java) inspired `unittest`.

So one way would be to rewrite all the tests to the pythonic lighter `py.test` style or to stick with `unittest` and rewrite the help page about testing. The big advantage of using a standard library module is that the users don't have to install anything (except python).

**Comment by Dog** [comment]
The advantage pytest gave is it allowed you to run all tests for all exercises at one time. It was implemented by the maintainer that came before me, and I just kept pytest because it was the one they had used.

**Comment by behrtam** [comment]
The failfast option for `unittest` was added in 2.7.

So maybe we should rewrite [TESTS.md](https://github.com/exercism/xpython/blob/master/docs/TESTS.md) to show the `unittest` way (without 3rd party packages) as the default option and mention `pytest` as simple possibility to run all tests for all exercises.

**Comment by Dog** [comment]
To make sure my last comment was understood, there is a difference between fail fast and failed first.

Fail fast may be available in unittest, but it does not support running the failed test first the next time it is run.

**Comment by behrtam** [comment]
Okay, so `pytest` adds the possibility to run the test first that failed in the last run.

Than I think we should rewrite the `docs/TEST.md` to first mention how to run the tests with the build-in tools and mention `pytest` (what, how, why) as addition.
