### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#329]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by behrtam** [comment]
The current status looks like this ...
- [X] alphabetic characters at the beginning of a valid binary number
- [X] alphabetic characters at the end of a valid binary number
- [ ] alphabetic characters in the middle of an otherwise valid binary number
- [X] invalid digits (e.g. 2)

So, we only need to add the case "10convert01" as suggested by @odeits.

**Comment by kytrinyx** [comment]
>  and create a .json file in x-common

Yeah, absolutely.

**Comment by patricksjackson** [comment]
Since binary is in the process of being deprecated (exercism/x-common#279) this issue can probably be closed.

**Comment by kytrinyx** [comment]
Yeah, I think you're right about that.
